"""add column comments

Revision ID: 9ccfc39f8962
Revises: cdc2ffe29606
Create Date: 2026-07-21 12:33:47.697234

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9ccfc39f8962"
down_revision: Union[str, Sequence[str], None] = "cdc2ffe29606"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "approvals",
        "id",
        existing_type=sa.INTEGER(),
        comment="PK",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "approvals",
        "item_id",
        existing_type=sa.INTEGER(),
        comment="대상 항목 FK",
        existing_nullable=False,
    )
    op.alter_column(
        "approvals",
        "submitter_id",
        existing_type=sa.INTEGER(),
        comment="상신자(담당자) FK",
        existing_nullable=False,
    )
    op.alter_column(
        "approvals",
        "memo",
        existing_type=sa.VARCHAR(),
        comment="상신 메모",
        existing_nullable=True,
    )
    op.alter_column(
        "approvals",
        "attachments",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="첨부 문서 목록({name,size})",
        existing_nullable=True,
    )
    op.alter_column(
        "approvals",
        "signed",
        existing_type=sa.BOOLEAN(),
        comment="전자서명 여부",
        existing_nullable=False,
    )
    op.alter_column(
        "approvals",
        "basis_note",
        existing_type=sa.VARCHAR(),
        comment="기준 근거 문구",
        existing_nullable=True,
    )
    op.alter_column(
        "approvals",
        "reviewer_id",
        existing_type=sa.INTEGER(),
        comment="검토자(관리자) FK",
        existing_nullable=True,
    )
    op.alter_column(
        "approvals",
        "decision",
        existing_type=sa.VARCHAR(length=9),
        comment="검토 결과(confirmed/rejected, 미검토 시 null)",
        existing_nullable=True,
    )
    op.alter_column(
        "approvals",
        "reviewed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="검토 일시",
        existing_nullable=True,
    )
    op.alter_column(
        "approvals",
        "submitted_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="상신 일시",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "cases",
        "id",
        existing_type=sa.INTEGER(),
        comment="PK",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "cases",
        "subject_name",
        existing_type=sa.VARCHAR(),
        comment="대상자(퇴사자) 이름",
        existing_nullable=False,
    )
    op.alter_column(
        "cases",
        "subject_job",
        existing_type=sa.VARCHAR(),
        comment="직무/직종",
        existing_nullable=False,
    )
    op.alter_column(
        "cases",
        "subject_rank",
        existing_type=sa.VARCHAR(),
        comment="직급",
        existing_nullable=False,
    )
    op.alter_column(
        "cases",
        "subject_role_title",
        existing_type=sa.VARCHAR(),
        comment="직책/역할명",
        existing_nullable=True,
    )
    op.alter_column(
        "cases",
        "exit_reason",
        existing_type=sa.VARCHAR(length=23),
        comment="퇴사 사유유형(voluntary/recommended_resignation/dismissal/contract_expiry)",
        existing_nullable=False,
    )
    op.alter_column(
        "cases",
        "reason_text",
        existing_type=sa.VARCHAR(),
        comment="회사사유 입력 텍스트(대조 엔진 입력원)",
        existing_nullable=True,
    )
    op.alter_column(
        "cases",
        "exit_date",
        existing_type=sa.DATE(),
        comment="퇴직 예정일(기한 계산 기준)",
        existing_nullable=False,
    )
    op.alter_column(
        "cases",
        "intake_route",
        existing_type=sa.VARCHAR(length=11),
        comment="케이스 접수경로(groupware/dismissal/resignation)",
        existing_nullable=False,
    )
    op.alter_column(
        "cases",
        "profile_id",
        existing_type=sa.INTEGER(),
        comment="적용 프로파일 FK(직무·직급→항목 자동배정)",
        existing_nullable=True,
    )
    op.alter_column(
        "cases",
        "status",
        existing_type=sa.VARCHAR(length=14),
        comment="케이스 진행상태(in_progress/review_waiting/completed)",
        existing_nullable=False,
    )
    op.alter_column(
        "cases",
        "created_by",
        existing_type=sa.INTEGER(),
        comment="접수 담당자 FK(User)",
        existing_nullable=False,
    )
    op.alter_column(
        "cases",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="생성 시각(UTC)",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "cases",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="수정 시각(UTC)",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "evidence",
        "id",
        existing_type=sa.INTEGER(),
        comment="PK",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "evidence",
        "case_id",
        existing_type=sa.INTEGER(),
        comment="소속 케이스 FK",
        existing_nullable=False,
    )
    op.alter_column(
        "evidence",
        "seq",
        existing_type=sa.INTEGER(),
        comment="처리 순번(case 내 단조증가, 체인 순서 조회 키)",
        existing_nullable=False,
    )
    op.alter_column(
        "evidence",
        "occurred_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="처리 일시",
        existing_nullable=False,
    )
    op.alter_column(
        "evidence",
        "actor",
        existing_type=sa.VARCHAR(),
        comment="수행자",
        existing_nullable=False,
    )
    op.alter_column(
        "evidence",
        "action",
        existing_type=sa.VARCHAR(),
        comment="처리 내용",
        existing_nullable=False,
    )
    op.alter_column(
        "evidence",
        "event_type",
        existing_type=sa.VARCHAR(length=18),
        comment="봉인 트리거 이벤트 종류",
        existing_nullable=False,
    )
    op.alter_column(
        "evidence",
        "origin",
        existing_type=sa.VARCHAR(length=6),
        comment="봉인 출처(auto=이벤트 자동 봉인/manual=수동 보충 봉인)",
        existing_nullable=False,
    )
    op.alter_column(
        "evidence",
        "document_ref",
        existing_type=sa.VARCHAR(),
        comment="관련 문서명",
        existing_nullable=True,
    )
    op.alter_column(
        "evidence",
        "payload",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="봉인 대상 스냅샷",
        existing_nullable=False,
    )
    op.alter_column(
        "evidence",
        "integrity_hash",
        existing_type=sa.VARCHAR(),
        comment="SHA-256 해시(payload 무결성)",
        existing_nullable=False,
    )
    op.alter_column(
        "evidence",
        "prev_hash",
        existing_type=sa.VARCHAR(),
        comment="직전 레코드 해시(체인 — 변경 탐지)",
        existing_nullable=True,
    )
    op.alter_column(
        "evidence",
        "sealed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="봉인 시각",
        existing_nullable=False,
    )
    op.alter_column(
        "items",
        "id",
        existing_type=sa.INTEGER(),
        comment="PK",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "items",
        "case_id",
        existing_type=sa.INTEGER(),
        comment="소속 케이스 FK",
        existing_nullable=False,
    )
    op.alter_column(
        "items",
        "rail",
        existing_type=sa.VARCHAR(length=12),
        comment="소속 레일(labor/trade_secret/security)",
        existing_nullable=False,
    )
    op.alter_column(
        "items",
        "code",
        existing_type=sa.VARCHAR(),
        comment="항목코드(레일 접두어 L-/S-/C-)",
        existing_nullable=False,
    )
    op.alter_column(
        "items",
        "name",
        existing_type=sa.VARCHAR(),
        comment="항목명",
        existing_nullable=False,
    )
    op.alter_column(
        "items",
        "kind",
        existing_type=sa.VARCHAR(length=11),
        comment="항목 구분(statutory/internal/recommended)",
        existing_nullable=False,
    )
    op.alter_column(
        "items",
        "status",
        existing_type=sa.VARCHAR(length=14),
        comment="검사항목 상태(pending/submitted/approved/rejected/not_applicable)",
        existing_nullable=False,
    )
    op.alter_column(
        "items",
        "blocking",
        existing_type=sa.BOOLEAN(),
        comment="게이트 차단 여부",
        existing_nullable=False,
    )
    op.alter_column(
        "items",
        "sub",
        existing_type=sa.VARCHAR(),
        comment="진행 요약 한 줄",
        existing_nullable=True,
    )
    op.alter_column(
        "items",
        "deadline",
        existing_type=sa.DATE(),
        comment="법정 기한일(있는 경우)",
        existing_nullable=True,
    )
    op.alter_column(
        "items",
        "standard_ids",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="근거 배지(Standard.id 목록)",
        existing_nullable=True,
    )
    op.alter_column(
        "items",
        "detail",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="레일별 상세 필드(노무 기한요소/영업비밀 자산요소/보안 회수대상)",
        existing_nullable=True,
    )
    op.alter_column(
        "items",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="생성 시각(UTC)",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "items",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="수정 시각(UTC)",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "labor_precedents",
        "id",
        existing_type=sa.INTEGER(),
        comment="PK",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "labor_precedents",
        "seq",
        existing_type=sa.INTEGER(),
        comment="CSV 순번(실측 사례 인용 참조키)",
        existing_nullable=False,
    )
    op.alter_column(
        "labor_precedents",
        "category",
        existing_type=sa.VARCHAR(length=22),
        comment="사건유형(CSV 자료구분)",
        existing_nullable=False,
    )
    op.alter_column(
        "labor_precedents",
        "title",
        existing_type=sa.VARCHAR(),
        comment="제목(한 줄 요지)",
        existing_nullable=False,
    )
    op.alter_column(
        "labor_precedents",
        "committee",
        existing_type=sa.VARCHAR(),
        comment="위원회명",
        existing_nullable=False,
    )
    op.alter_column(
        "labor_precedents",
        "decided_on",
        existing_type=sa.DATE(),
        comment="작성일자",
        existing_nullable=True,
    )
    op.alter_column(
        "labor_precedents",
        "views",
        existing_type=sa.INTEGER(),
        comment="조회수",
        existing_nullable=True,
    )
    op.alter_column(
        "labor_precedents",
        "case_no",
        existing_type=sa.VARCHAR(),
        comment="사건번호(제목에서 추출, 약 27%만 존재)",
        existing_nullable=True,
    )
    op.alter_column(
        "labor_precedents",
        "matched_elements",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="이 판정례가 커버하는 판정 요구 요소 목록(대조 매칭 대상)",
        existing_nullable=False,
    )
    op.alter_column(
        "labor_precedents",
        "is_seed",
        existing_type=sa.BOOLEAN(),
        comment="데모 직결 실측 사례 표시(순번 51·388=true)",
        existing_nullable=False,
    )
    op.alter_column(
        "labor_precedents",
        "ingested_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="코퍼스 적재 시각",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "profiles",
        "id",
        existing_type=sa.INTEGER(),
        comment="PK",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "profiles",
        "name",
        existing_type=sa.VARCHAR(),
        comment="프로파일 이름",
        existing_nullable=False,
    )
    op.alter_column(
        "profiles",
        "job",
        existing_type=sa.VARCHAR(),
        comment="직종 축",
        existing_nullable=True,
    )
    op.alter_column(
        "profiles",
        "rank",
        existing_type=sa.VARCHAR(),
        comment="직급 축",
        existing_nullable=True,
    )
    op.alter_column(
        "profiles",
        "rail_map",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="레일별 적용 RailTemplate 매핑({labor,trade_secret,security → rail_template_id})",
        existing_nullable=False,
    )
    op.alter_column(
        "rail_templates",
        "id",
        existing_type=sa.INTEGER(),
        comment="PK",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "rail_templates",
        "rail",
        existing_type=sa.VARCHAR(length=12),
        comment="소속 레일",
        existing_nullable=False,
    )
    op.alter_column(
        "rail_templates",
        "name",
        existing_type=sa.VARCHAR(),
        comment="템플릿 이름",
        existing_nullable=False,
    )
    op.alter_column(
        "rail_templates",
        "is_base",
        existing_type=sa.BOOLEAN(),
        comment="기본 제공 템플릿 여부(vs 회사 커스텀)",
        existing_nullable=False,
    )
    op.alter_column(
        "standards",
        "id",
        existing_type=sa.INTEGER(),
        comment="PK",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "standards",
        "tier",
        existing_type=sa.VARCHAR(length=2),
        comment="근거 층위(L1/L2/L3)",
        existing_nullable=False,
    )
    op.alter_column(
        "standards",
        "rail",
        existing_type=sa.VARCHAR(length=12),
        comment="소속 레일",
        existing_nullable=False,
    )
    op.alter_column(
        "standards",
        "title",
        existing_type=sa.VARCHAR(),
        comment="근거 제목",
        existing_nullable=False,
    )
    op.alter_column(
        "standards",
        "article",
        existing_type=sa.VARCHAR(),
        comment="조문/요지",
        existing_nullable=True,
    )
    op.alter_column(
        "standards",
        "body",
        existing_type=sa.VARCHAR(),
        comment="인용 원문",
        existing_nullable=True,
    )
    op.alter_column(
        "standards",
        "source_url",
        existing_type=sa.VARCHAR(),
        comment="원문 링크",
        existing_nullable=True,
    )
    op.alter_column(
        "standards",
        "version",
        existing_type=sa.VARCHAR(),
        comment="근거 버전",
        existing_nullable=False,
    )
    op.alter_column(
        "standards",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="최신 반영 시각",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "template_items",
        "id",
        existing_type=sa.INTEGER(),
        comment="PK",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "template_items",
        "rail_template_id",
        existing_type=sa.INTEGER(),
        comment="소속 템플릿 FK",
        existing_nullable=False,
    )
    op.alter_column(
        "template_items",
        "code",
        existing_type=sa.VARCHAR(),
        comment="항목코드(레일 접두어 L-/S-/C-)",
        existing_nullable=False,
    )
    op.alter_column(
        "template_items",
        "name",
        existing_type=sa.VARCHAR(),
        comment="항목명",
        existing_nullable=False,
    )
    op.alter_column(
        "template_items",
        "kind",
        existing_type=sa.VARCHAR(length=11),
        comment="항목 구분(statutory/internal/recommended)",
        existing_nullable=False,
    )
    op.alter_column(
        "template_items",
        "blocking",
        existing_type=sa.BOOLEAN(),
        comment="게이트 차단 여부(기본 kind==statutory)",
        existing_nullable=False,
    )
    op.alter_column(
        "template_items",
        "standard_ids",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="근거(Standard.id 목록)",
        existing_nullable=True,
    )
    op.alter_column(
        "template_items",
        "detail_schema",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="레일별 상세 필드 스키마 예약",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "id",
        existing_type=sa.INTEGER(),
        comment="PK",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "users",
        "name",
        existing_type=sa.VARCHAR(),
        comment="사용자 이름",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(),
        comment="로그인 ID",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "role",
        existing_type=sa.VARCHAR(length=5),
        comment="사용자 역할(admin/user)",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "granted_scopes",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        comment="admin이 부여한 권한 목록(상신/레일수행/승인)",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "granted_scopes",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        comment=None,
        existing_comment="admin이 부여한 권한 목록(상신/레일수행/승인)",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "role",
        existing_type=sa.VARCHAR(length=5),
        comment=None,
        existing_comment="사용자 역할(admin/user)",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="로그인 ID",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "name",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="사용자 이름",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="PK",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "template_items",
        "detail_schema",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=None,
        existing_comment="레일별 상세 필드 스키마 예약",
        existing_nullable=True,
    )
    op.alter_column(
        "template_items",
        "standard_ids",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=None,
        existing_comment="근거(Standard.id 목록)",
        existing_nullable=True,
    )
    op.alter_column(
        "template_items",
        "blocking",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="게이트 차단 여부(기본 kind==statutory)",
        existing_nullable=False,
    )
    op.alter_column(
        "template_items",
        "kind",
        existing_type=sa.VARCHAR(length=11),
        comment=None,
        existing_comment="항목 구분(statutory/internal/recommended)",
        existing_nullable=False,
    )
    op.alter_column(
        "template_items",
        "name",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="항목명",
        existing_nullable=False,
    )
    op.alter_column(
        "template_items",
        "code",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="항목코드(레일 접두어 L-/S-/C-)",
        existing_nullable=False,
    )
    op.alter_column(
        "template_items",
        "rail_template_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="소속 템플릿 FK",
        existing_nullable=False,
    )
    op.alter_column(
        "template_items",
        "id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="PK",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "standards",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="최신 반영 시각",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "standards",
        "version",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="근거 버전",
        existing_nullable=False,
    )
    op.alter_column(
        "standards",
        "source_url",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="원문 링크",
        existing_nullable=True,
    )
    op.alter_column(
        "standards",
        "body",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="인용 원문",
        existing_nullable=True,
    )
    op.alter_column(
        "standards",
        "article",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="조문/요지",
        existing_nullable=True,
    )
    op.alter_column(
        "standards",
        "title",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="근거 제목",
        existing_nullable=False,
    )
    op.alter_column(
        "standards",
        "rail",
        existing_type=sa.VARCHAR(length=12),
        comment=None,
        existing_comment="소속 레일",
        existing_nullable=False,
    )
    op.alter_column(
        "standards",
        "tier",
        existing_type=sa.VARCHAR(length=2),
        comment=None,
        existing_comment="근거 층위(L1/L2/L3)",
        existing_nullable=False,
    )
    op.alter_column(
        "standards",
        "id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="PK",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "rail_templates",
        "is_base",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="기본 제공 템플릿 여부(vs 회사 커스텀)",
        existing_nullable=False,
    )
    op.alter_column(
        "rail_templates",
        "name",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="템플릿 이름",
        existing_nullable=False,
    )
    op.alter_column(
        "rail_templates",
        "rail",
        existing_type=sa.VARCHAR(length=12),
        comment=None,
        existing_comment="소속 레일",
        existing_nullable=False,
    )
    op.alter_column(
        "rail_templates",
        "id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="PK",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "profiles",
        "rail_map",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=None,
        existing_comment="레일별 적용 RailTemplate 매핑({labor,trade_secret,security → rail_template_id})",
        existing_nullable=False,
    )
    op.alter_column(
        "profiles",
        "rank",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="직급 축",
        existing_nullable=True,
    )
    op.alter_column(
        "profiles",
        "job",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="직종 축",
        existing_nullable=True,
    )
    op.alter_column(
        "profiles",
        "name",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="프로파일 이름",
        existing_nullable=False,
    )
    op.alter_column(
        "profiles",
        "id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="PK",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "labor_precedents",
        "ingested_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="코퍼스 적재 시각",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "labor_precedents",
        "is_seed",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="데모 직결 실측 사례 표시(순번 51·388=true)",
        existing_nullable=False,
    )
    op.alter_column(
        "labor_precedents",
        "matched_elements",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=None,
        existing_comment="이 판정례가 커버하는 판정 요구 요소 목록(대조 매칭 대상)",
        existing_nullable=False,
    )
    op.alter_column(
        "labor_precedents",
        "case_no",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="사건번호(제목에서 추출, 약 27%만 존재)",
        existing_nullable=True,
    )
    op.alter_column(
        "labor_precedents",
        "views",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="조회수",
        existing_nullable=True,
    )
    op.alter_column(
        "labor_precedents",
        "decided_on",
        existing_type=sa.DATE(),
        comment=None,
        existing_comment="작성일자",
        existing_nullable=True,
    )
    op.alter_column(
        "labor_precedents",
        "committee",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="위원회명",
        existing_nullable=False,
    )
    op.alter_column(
        "labor_precedents",
        "title",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="제목(한 줄 요지)",
        existing_nullable=False,
    )
    op.alter_column(
        "labor_precedents",
        "category",
        existing_type=sa.VARCHAR(length=22),
        comment=None,
        existing_comment="사건유형(CSV 자료구분)",
        existing_nullable=False,
    )
    op.alter_column(
        "labor_precedents",
        "seq",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="CSV 순번(실측 사례 인용 참조키)",
        existing_nullable=False,
    )
    op.alter_column(
        "labor_precedents",
        "id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="PK",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "items",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="수정 시각(UTC)",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "items",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="생성 시각(UTC)",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "items",
        "detail",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=None,
        existing_comment="레일별 상세 필드(노무 기한요소/영업비밀 자산요소/보안 회수대상)",
        existing_nullable=True,
    )
    op.alter_column(
        "items",
        "standard_ids",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=None,
        existing_comment="근거 배지(Standard.id 목록)",
        existing_nullable=True,
    )
    op.alter_column(
        "items",
        "deadline",
        existing_type=sa.DATE(),
        comment=None,
        existing_comment="법정 기한일(있는 경우)",
        existing_nullable=True,
    )
    op.alter_column(
        "items",
        "sub",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="진행 요약 한 줄",
        existing_nullable=True,
    )
    op.alter_column(
        "items",
        "blocking",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="게이트 차단 여부",
        existing_nullable=False,
    )
    op.alter_column(
        "items",
        "status",
        existing_type=sa.VARCHAR(length=14),
        comment=None,
        existing_comment="검사항목 상태(pending/submitted/approved/rejected/not_applicable)",
        existing_nullable=False,
    )
    op.alter_column(
        "items",
        "kind",
        existing_type=sa.VARCHAR(length=11),
        comment=None,
        existing_comment="항목 구분(statutory/internal/recommended)",
        existing_nullable=False,
    )
    op.alter_column(
        "items",
        "name",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="항목명",
        existing_nullable=False,
    )
    op.alter_column(
        "items",
        "code",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="항목코드(레일 접두어 L-/S-/C-)",
        existing_nullable=False,
    )
    op.alter_column(
        "items",
        "rail",
        existing_type=sa.VARCHAR(length=12),
        comment=None,
        existing_comment="소속 레일(labor/trade_secret/security)",
        existing_nullable=False,
    )
    op.alter_column(
        "items",
        "case_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="소속 케이스 FK",
        existing_nullable=False,
    )
    op.alter_column(
        "items",
        "id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="PK",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "evidence",
        "sealed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="봉인 시각",
        existing_nullable=False,
    )
    op.alter_column(
        "evidence",
        "prev_hash",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="직전 레코드 해시(체인 — 변경 탐지)",
        existing_nullable=True,
    )
    op.alter_column(
        "evidence",
        "integrity_hash",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="SHA-256 해시(payload 무결성)",
        existing_nullable=False,
    )
    op.alter_column(
        "evidence",
        "payload",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=None,
        existing_comment="봉인 대상 스냅샷",
        existing_nullable=False,
    )
    op.alter_column(
        "evidence",
        "document_ref",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="관련 문서명",
        existing_nullable=True,
    )
    op.alter_column(
        "evidence",
        "origin",
        existing_type=sa.VARCHAR(length=6),
        comment=None,
        existing_comment="봉인 출처(auto=이벤트 자동 봉인/manual=수동 보충 봉인)",
        existing_nullable=False,
    )
    op.alter_column(
        "evidence",
        "event_type",
        existing_type=sa.VARCHAR(length=18),
        comment=None,
        existing_comment="봉인 트리거 이벤트 종류",
        existing_nullable=False,
    )
    op.alter_column(
        "evidence",
        "action",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="처리 내용",
        existing_nullable=False,
    )
    op.alter_column(
        "evidence",
        "actor",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="수행자",
        existing_nullable=False,
    )
    op.alter_column(
        "evidence",
        "occurred_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="처리 일시",
        existing_nullable=False,
    )
    op.alter_column(
        "evidence",
        "seq",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="처리 순번(case 내 단조증가, 체인 순서 조회 키)",
        existing_nullable=False,
    )
    op.alter_column(
        "evidence",
        "case_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="소속 케이스 FK",
        existing_nullable=False,
    )
    op.alter_column(
        "evidence",
        "id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="PK",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "cases",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="수정 시각(UTC)",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "cases",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="생성 시각(UTC)",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "cases",
        "created_by",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="접수 담당자 FK(User)",
        existing_nullable=False,
    )
    op.alter_column(
        "cases",
        "status",
        existing_type=sa.VARCHAR(length=14),
        comment=None,
        existing_comment="케이스 진행상태(in_progress/review_waiting/completed)",
        existing_nullable=False,
    )
    op.alter_column(
        "cases",
        "profile_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="적용 프로파일 FK(직무·직급→항목 자동배정)",
        existing_nullable=True,
    )
    op.alter_column(
        "cases",
        "intake_route",
        existing_type=sa.VARCHAR(length=11),
        comment=None,
        existing_comment="케이스 접수경로(groupware/dismissal/resignation)",
        existing_nullable=False,
    )
    op.alter_column(
        "cases",
        "exit_date",
        existing_type=sa.DATE(),
        comment=None,
        existing_comment="퇴직 예정일(기한 계산 기준)",
        existing_nullable=False,
    )
    op.alter_column(
        "cases",
        "reason_text",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="회사사유 입력 텍스트(대조 엔진 입력원)",
        existing_nullable=True,
    )
    op.alter_column(
        "cases",
        "exit_reason",
        existing_type=sa.VARCHAR(length=23),
        comment=None,
        existing_comment="퇴사 사유유형(voluntary/recommended_resignation/dismissal/contract_expiry)",
        existing_nullable=False,
    )
    op.alter_column(
        "cases",
        "subject_role_title",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="직책/역할명",
        existing_nullable=True,
    )
    op.alter_column(
        "cases",
        "subject_rank",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="직급",
        existing_nullable=False,
    )
    op.alter_column(
        "cases",
        "subject_job",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="직무/직종",
        existing_nullable=False,
    )
    op.alter_column(
        "cases",
        "subject_name",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="대상자(퇴사자) 이름",
        existing_nullable=False,
    )
    op.alter_column(
        "cases",
        "id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="PK",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "approvals",
        "submitted_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="상신 일시",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "approvals",
        "reviewed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="검토 일시",
        existing_nullable=True,
    )
    op.alter_column(
        "approvals",
        "decision",
        existing_type=sa.VARCHAR(length=9),
        comment=None,
        existing_comment="검토 결과(confirmed/rejected, 미검토 시 null)",
        existing_nullable=True,
    )
    op.alter_column(
        "approvals",
        "reviewer_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="검토자(관리자) FK",
        existing_nullable=True,
    )
    op.alter_column(
        "approvals",
        "basis_note",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="기준 근거 문구",
        existing_nullable=True,
    )
    op.alter_column(
        "approvals",
        "signed",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="전자서명 여부",
        existing_nullable=False,
    )
    op.alter_column(
        "approvals",
        "attachments",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=None,
        existing_comment="첨부 문서 목록({name,size})",
        existing_nullable=True,
    )
    op.alter_column(
        "approvals",
        "memo",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="상신 메모",
        existing_nullable=True,
    )
    op.alter_column(
        "approvals",
        "submitter_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="상신자(담당자) FK",
        existing_nullable=False,
    )
    op.alter_column(
        "approvals",
        "item_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="대상 항목 FK",
        existing_nullable=False,
    )
    op.alter_column(
        "approvals",
        "id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="PK",
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
