"""core schema: case/item/approval/evidence/standard/template/profile/user

Revision ID: af86fe666b76
Revises:
Create Date: 2026-07-20 19:50:09.884907

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "af86fe666b76"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("job", sa.String(), nullable=True),
        sa.Column("rank", sa.String(), nullable=True),
        sa.Column("rail_map", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profiles")),
    )
    op.create_table(
        "rail_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "rail",
            sa.Enum(
                "labor",
                "trade_secret",
                "security",
                name="rail",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_base", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rail_templates")),
    )
    op.create_table(
        "standards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "tier",
            sa.Enum(
                "L1",
                "L2",
                "L3",
                name="standardtier",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "rail",
            sa.Enum(
                "labor",
                "trade_secret",
                "security",
                name="rail",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("article", sa.String(), nullable=True),
        sa.Column("body", sa.String(), nullable=True),
        sa.Column("source_url", sa.String(), nullable=True),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_standards")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "admin", "user", name="role", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("granted_scopes", postgresql.ARRAY(sa.String()), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "cases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subject_name", sa.String(), nullable=False),
        sa.Column("subject_job", sa.String(), nullable=False),
        sa.Column("subject_rank", sa.String(), nullable=False),
        sa.Column("subject_role_title", sa.String(), nullable=True),
        sa.Column(
            "exit_reason",
            sa.Enum(
                "voluntary",
                "recommended_resignation",
                "dismissal",
                "contract_expiry",
                name="exitreason",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("reason_text", sa.String(), nullable=True),
        sa.Column("exit_date", sa.Date(), nullable=False),
        sa.Column(
            "intake_route",
            sa.Enum(
                "groupware",
                "dismissal",
                "resignation",
                name="intakeroute",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("profile_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "in_progress",
                "review_waiting",
                "completed",
                name="casestatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_cases_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["profiles.id"], name=op.f("fk_cases_profile_id_profiles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cases")),
    )
    op.create_index(op.f("ix_cases_created_by"), "cases", ["created_by"], unique=False)
    op.create_index(op.f("ix_cases_profile_id"), "cases", ["profile_id"], unique=False)
    op.create_table(
        "template_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rail_template_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "statutory",
                "internal",
                "recommended",
                name="itemkind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("blocking", sa.Boolean(), nullable=False),
        sa.Column(
            "standard_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "detail_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["rail_template_id"],
            ["rail_templates.id"],
            name=op.f("fk_template_items_rail_template_id_rail_templates"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_template_items")),
    )
    op.create_index(
        op.f("ix_template_items_rail_template_id"),
        "template_items",
        ["rail_template_id"],
        unique=False,
    )
    op.create_table(
        "evidence",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "item_submitted",
                "item_confirmed",
                "item_rejected",
                "compare_recorded",
                "recovery_confirmed",
                "case_approved",
                name="evidenceeventtype",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "origin",
            sa.Enum(
                "auto",
                "manual",
                name="evidenceorigin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("document_ref", sa.String(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("integrity_hash", sa.String(), nullable=False),
        sa.Column("prev_hash", sa.String(), nullable=True),
        sa.Column("sealed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_evidence_case_id_cases")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
        sa.UniqueConstraint("case_id", "seq", name="uq_evidence_case_id_seq"),
    )
    op.create_table(
        "items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column(
            "rail",
            sa.Enum(
                "labor",
                "trade_secret",
                "security",
                name="rail",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "statutory",
                "internal",
                "recommended",
                name="itemkind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "submitted",
                "approved",
                "rejected",
                "not_applicable",
                name="itemstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("blocking", sa.Boolean(), nullable=False),
        sa.Column("sub", sa.String(), nullable=True),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column(
            "standard_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_items_case_id_cases")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_items")),
    )
    op.create_index(
        "ix_items_case_id_status", "items", ["case_id", "status"], unique=False
    )
    op.create_table(
        "approvals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("submitter_id", sa.Integer(), nullable=False),
        sa.Column("memo", sa.String(), nullable=True),
        sa.Column(
            "attachments", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("signed", sa.Boolean(), nullable=False),
        sa.Column("basis_note", sa.String(), nullable=True),
        sa.Column("reviewer_id", sa.Integer(), nullable=True),
        sa.Column(
            "decision",
            sa.Enum(
                "confirmed",
                "rejected",
                name="approvaldecision",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["items.id"], name=op.f("fk_approvals_item_id_items")
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"], ["users.id"], name=op.f("fk_approvals_reviewer_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["submitter_id"], ["users.id"], name=op.f("fk_approvals_submitter_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
    )
    op.create_index(
        op.f("ix_approvals_item_id"), "approvals", ["item_id"], unique=False
    )
    op.create_index(
        op.f("ix_approvals_reviewer_id"), "approvals", ["reviewer_id"], unique=False
    )
    op.create_index(
        op.f("ix_approvals_submitter_id"), "approvals", ["submitter_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_approvals_submitter_id"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_reviewer_id"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_item_id"), table_name="approvals")
    op.drop_table("approvals")
    op.drop_index("ix_items_case_id_status", table_name="items")
    op.drop_table("items")
    op.drop_table("evidence")
    op.drop_index(
        op.f("ix_template_items_rail_template_id"), table_name="template_items"
    )
    op.drop_table("template_items")
    op.drop_index(op.f("ix_cases_profile_id"), table_name="cases")
    op.drop_index(op.f("ix_cases_created_by"), table_name="cases")
    op.drop_table("cases")
    op.drop_table("users")
    op.drop_table("standards")
    op.drop_table("rail_templates")
    op.drop_table("profiles")
    # ### end Alembic commands ###
