"""labor precedent corpus

Revision ID: cdc2ffe29606
Revises: af86fe666b76
Create Date: 2026-07-21 12:10:01.178458

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cdc2ffe29606"
down_revision: Union[str, Sequence[str], None] = "af86fe666b76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "labor_precedents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "disciplinary_dismissal",
                "unfair_labor_practice",
                "ordinary_dismissal",
                "term_expiry",
                "fair_representation",
                "other_discipline",
                "remedy_interest",
                "managerial_dismissal",
                "resignation",
                "party_standing",
                "bargaining_rep",
                "bargaining_unit",
                "transfer",
                "bargaining_notice",
                "discrimination",
                "ex_officio_dismissal",
                "standby_order",
                "suspension",
                name="laborcasetype",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("committee", sa.String(), nullable=False),
        sa.Column("decided_on", sa.Date(), nullable=True),
        sa.Column("views", sa.Integer(), nullable=True),
        sa.Column("case_no", sa.String(), nullable=True),
        sa.Column(
            "matched_elements", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("is_seed", sa.Boolean(), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_labor_precedents")),
        sa.UniqueConstraint("seq", name=op.f("uq_labor_precedents_seq")),
    )
    op.create_index(
        "ix_labor_precedents_category", "labor_precedents", ["category"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_labor_precedents_category", table_name="labor_precedents")
    op.drop_table("labor_precedents")
    # ### end Alembic commands ###
